repository:
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

  delete_branch_on_merge: true

  allow_auto_merge: true

  default_branch: main

  name: go-pihole
  description: A Golang Pi-hole client
  topics: pihole, golang

branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - test
          - lint
          - acceptance
